<a href="https://colab.research.google.com/github/abalckpie/professorahn/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%97%AD%EB%9F%89_%EC%97%B0%EB%A0%B9%EB%8C%80%EB%B3%84_%ED%8F%89%EA%B7%A0%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. 데이터 불러오기

In [26]:
import pandas as pd
import numpy as np
csv_test = pd.read_csv('/content/2022_2022년 지능정보사회 이용자 패널 조사_Data(가중치포함).csv')
df = pd.DataFrame(csv_test)
df

,No,wgt_a,wgt_b,id,Josagu,Josagu_gubun,Bon,Area1,Area2,Area3,...,DQ4_1,DQ4_2,DQ4_3,DQ4_4,DQ4_op2,DQ4_op3,DQ4_op4,DQ5,DQ6,DQ7
0,1,9115.936286,1.249960,2_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3
1,2,7379.420451,1.011852,6_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4,4,5
2,3,11069.130680,1.517778,8_2,11010730061,2,1,1,113,3,...,NaN,NaN,NaN,4.0,NaN,NaN,1.0,6,10,3
3,4,5461.096385,0.748815,8_3,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,7,10,3
4,5,2308.647665,0.316557,9_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373,5374,5214.785929,0.715042,204405_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,10,4
5374,5375,3682.940899,0.504998,204411_1,11250730521,2,2,1,116,3,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,5,10,4
5375,5376,5807.987516,0.796380,204411_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,10,4
5376,5377,2455.293933,0.336665,204417_1,11250730521,2,2,1,116,3,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,7,7,4
5377,5378,3476.523952,0.476694,204417_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,7,4

2. 필요한 데이터 추출

In [18]:
df.columns
df[['Age_group', 'Q30_1', 'Q30_2', 'Q30_3', 'Q30_4', 'Q30_5', 'Q30_6']]
df1 = df[['Age_group', 'Q30_1', 'Q30_2', 'Q30_3', 'Q30_4', 'Q30_5', 'Q30_6']]
df1

      Age_group  Q30_1  Q30_2  Q30_3  Q30_4  Q30_5  Q30_6
0             6      3      2      3      4      3      3
1             5      4      4      1      3      4      4
2             5      5      5      5      5      5      5
3             2      3      3      2      2      3      3
4             4      4      4      4      5      4      3
...         ...    ...    ...    ...    ...    ...    ...
5373          1      4      4      4      4      3      4
5374          4      4      4      4      4      4      4
5375          1      4      4      4      4      4      4
5376          4      4      4      4      4      4      4
5377          1      4      4      4      4      3      4

[5378 rows x 7 columns]

3. 연령 그룹에 따른 문항별 평균값 구하기

In [28]:
df1.groupby(by='Age_group').mean().reset_index()
df1_1=df1.groupby(by='Age_group').mean().reset_index()
df1_1

   Age_group     Q30_1     Q30_2     Q30_3     Q30_4     Q30_5     Q30_6
0          1  3.818462  3.920000  3.553846  3.772308  3.332308  3.932308
1          2  4.084670  4.106061  3.984848  4.012478  3.874332  4.053476
2          3  4.015182  3.980769  3.924089  3.970648  3.788462  3.948381
3          4  3.859903  3.882126  3.723671  3.838647  3.610628  3.835749
4          5  3.534562  3.594470  3.436866  3.499539  3.250691  3.566820
5          6  3.000000  3.035237  2.927096  2.997570  2.731470  3.037667

4. 연령 제거 후 그룹에 따른 전체 평균 구하기

In [37]:
del df1_1['Age_group']
df1_1.mean(axis='columns')

0    3.721538
1    4.019311
2    3.937922
3    3.791787
4    3.480492
5    2.954840
dtype: float64

외 5개 문항 동일하게 작업

In [38]:
df2 = df[['Age_group', 'Q30_7', 'Q30_8', 'Q30_9', 'Q30_10', 'Q30_11']]
df2.groupby(by='Age_group').mean().reset_index()
df2_1=df2.groupby(by='Age_group').mean().reset_index()
df2_1
del df2_1['Age_group']
df2_1.mean(axis='columns')

0    3.163692
1    3.378253
2    3.331781
3    3.168309
4    2.924977
5    2.525881
dtype: float64

In [39]:
df3 = df[['Age_group', 'Q30_12', 'Q30_13', 'Q30_14', 'Q30_15']]
df3.groupby(by='Age_group').mean().reset_index()
df3_1=df3.groupby(by='Age_group').mean().reset_index()
df3_1
del df3_1['Age_group']
df3_1.mean(axis='columns')

0    3.504615
1    3.649955
2    3.505567
3    3.385749
4    3.181336
5    2.725699
dtype: float64

In [33]:
df4 = df[['Age_group', 'Q30_16', 'Q30_17', 'Q30_18']]
df4.groupby(by='Age_group').mean().reset_index()
df4_1=df4.groupby(by='Age_group').mean().reset_index()
df4_1
del df4_1['Age_group']
df4_1.mean(axis='columns')

0    2.816154
1    3.149955
2    3.282895
3    3.369082
4    3.312212
5    3.253341
dtype: float64

In [40]:
df5 = df[['Age_group', 'Q30_19', 'Q30_20', 'Q30_21']]
df5.groupby(by='Age_group').mean().reset_index()
df5_1=df5.groupby(by='Age_group').mean().reset_index()
df5_1
del df5_1['Age_group']
df5_1.mean(axis='columns')

0    3.102564
1    3.426619
2    3.382928
3    3.216103
4    2.969892
5    2.529769
dtype: float64

In [41]:
df6 = df[['Age_group', 'Q30_22', 'Q30_23', 'Q30_24']]
df6.groupby(by='Age_group').mean().reset_index()
df6_1=df6.groupby(by='Age_group').mean().reset_index()
df6_1
del df6_1['Age_group']
df6_1.mean(axis='columns')

0    3.447179
1    3.651218
2    3.413630
3    3.211272
4    2.878955
5    2.409072
dtype: float64