<a href="https://colab.research.google.com/github/abalckpie/professorahn/blob/main/%EC%86%8C%EB%85%BC%EB%AC%B8_1%EC%A0%88~%EB%8B%A8%EC%88%9C%ED%8F%89%EA%B7%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd
import numpy as np
import scipy.stats as stats
csv_test = pd.read_csv('/content/2022_2022년 지능정보사회 이용자 패널 조사_Data(가중치포함).csv')
df = pd.DataFrame(csv_test)
df

,No,wgt_a,wgt_b,id,Josagu,Josagu_gubun,Bon,Area1,Area2,Area3,...,DQ4_1,DQ4_2,DQ4_3,DQ4_4,DQ4_op2,DQ4_op3,DQ4_op4,DQ5,DQ6,DQ7
0,1,9115.936286,1.249960,2_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3
1,2,7379.420451,1.011852,6_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4,4,5
2,3,11069.130680,1.517778,8_2,11010730061,2,1,1,113,3,...,NaN,NaN,NaN,4.0,NaN,NaN,1.0,6,10,3
3,4,5461.096385,0.748815,8_3,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,7,10,3
4,5,2308.647665,0.316557,9_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373,5374,5214.785929,0.715042,204405_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,10,4
5374,5375,3682.940899,0.504998,204411_1,11250730521,2,2,1,116,3,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,5,10,4
5375,5376,5807.987516,0.796380,204411_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,10,4
5376,5377,2455.293933,0.336665,204417_1,11250730521,2,2,1,116,3,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,7,7,4
5377,5378,3476.523952,0.476694,204417_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,7,4

1. 연령별 평균치 확인

In [64]:
columns_to_check = ['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']
filtered_df = df[~df[columns_to_check].isin([9]).any(axis=1)]
print(filtered_df)

        No         wgt_a     wgt_b        id       Josagu  Josagu_gubun  Bon  \
0        1   9115.936286  1.249960       2_1  11010730061             2    1
2        3  11069.130680  1.517778       8_2  11010730061             2    1
3        4   5461.096385  0.748815       8_3  11010730061             2    1
4        5   2308.647665  0.316557       9_1  11010730061             2    1
5        6   7379.420451  1.011852      10_1  11010730061             2    1
...    ...           ...       ...       ...          ...           ...  ...
5373  5374   5214.785929  0.715042  204405_2  11250730521             2    2
5374  5375   3682.940899  0.504998  204411_1  11250730521             2    2
5375  5376   5807.987516  0.796380  204411_2  11250730521             2    2
5376  5377   2455.293933  0.336665  204417_1  11250730521             2    2
5377  5378   3476.523952  0.476694  204417_2  11250730521             2    2

      Area1  Area2  Area3  ...  DQ4_1  DQ4_2  DQ4_3  DQ4_4  DQ4_op2  DQ4_op3  \
0         1    113      3  ...    1.0    NaN    NaN    NaN      NaN      NaN
2         1    113      3  ...    NaN    NaN    NaN    4.0      NaN      NaN
3         1    113      3  ...    1.0    NaN    NaN    NaN      NaN      NaN
4         1    113      3  ...    1.0    NaN    NaN    NaN      NaN      NaN
5         1    113      3  ...    1.0    NaN    NaN    NaN      NaN      NaN
...     ...    ...    ...  ...    ...    ...    ...    ...      ...      ...
5373      1    116      3  ...    1.0    NaN    NaN    NaN      NaN      NaN
5374      1    116      3  ...    NaN    NaN    3.0    NaN      NaN      1.0
5375      1    116      3  ...    1.0    NaN    NaN    NaN      NaN      NaN
5376      1    116      3  ...    NaN    NaN    3.0    NaN      NaN      1.0
5377      1    116      3  ...    1.0    NaN    NaN    NaN      NaN      NaN

      DQ4_op4  DQ5  DQ6  DQ7
0         NaN    4    4    3
2         1.0    6   10    3
3         NaN    7   10    3
4         NaN    5    5    4
5         NaN    4    4    5
...       ...  ...  ...  ...
5373      NaN   11   10    4
5374      NaN    5   10    4
5375      NaN   11   10    4
5376      NaN    7    7    4
5377      NaN   11    7    4

[4567 rows x 404 columns]

In [65]:
filtered_df.columns
filtered_df[['Age_group', 'Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1 = filtered_df[['Age_group', 'Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1

      Age_group  Q1_1  Q1_2  Q1_3  Q1_4  Q1_5  Q1_6  Q1_7  Q1_8  Q1_9  Q1_10
0             6     3     2     1     3     2     2     3     4     3      2
2             5     4     3     3     4     3     4     3     3     4      3
3             2     3     2     3     3     2     4     3     3     3      3
4             4     3     3     2     3     4     4     3     2     2      3
5             5     3     3     2     1     3     3     4     3     2      2
...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
5373          1     3     3     3     3     4     4     4     4     2      3
5374          4     2     2     2     2     3     3     3     3     2      3
5375          1     3     3     3     4     4     4     4     4     3      3
5376          4     3     3     3     3     4     4     4     4     2      3
5377          1     2     2     2     2     3     3     3     3     2      3

[4567 rows x 11 columns]

In [69]:
df1.groupby(by='Age_group').mean().reset_index()
df1_1=df1.groupby(by='Age_group').mean().reset_index()
df1_1

,Age_group,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q1_8,Q1_9,Q1_10
0,1,3.193220,3.162712,3.071186,3.247458,3.464407,3.532203,3.433898,3.488136,3.081356,3.244068
1,2,3.324821,3.339122,3.185904,3.366701,3.467824,3.582227,3.561798,3.534219,3.187947,3.412666
2,3,3.159091,3.244019,2.984450,3.116029,3.299043,3.461722,3.436603,3.423445,2.952153,3.181818
3,4,3.072331,3.171068,2.887486,3.044776,3.316877,3.417910,3.437428,3.396096,2.840413,3.075775
4,5,2.817059,2.925926,2.603816,2.769921,3.016835,3.184063,3.190797,3.115600,2.566779,2.806958
5,6,2.505036,2.657554,2.279137,2.458993,2.729496,2.877698,2.943885,2.797122,2.300719,2.538129

In [67]:
del df1_1['Age_group']
df1_1.mean(axis='columns')

0    3.291864
1    3.396323
2    3.225837
3    3.166016
4    2.899776
5    2.608777
dtype: float64

1-1. ANOVA 시행

In [44]:
df_mean = pd.DataFrame()
df1['Mean_Q1'] = df1[['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']].mean(axis=1)
df_mean = df1[['Age_group', 'Mean_Q1']]
df_mean

<ipython-input-44-7be0e840e2db>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Mean_Q1'] = df1[['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']].mean(axis=1)

      Age_group  Mean_Q1
0             6      2.5
2             5      3.4
3             2      2.9
4             4      2.9
5             5      2.6
...         ...      ...
5373          1      3.3
5374          4      2.5
5375          1      3.5
5376          4      3.3
5377          1      2.5

[4567 rows x 2 columns]

In [13]:
grouped_data = [df_mean[df_mean['Age_group'] == group]['Mean_Q1'] for group in df['Age_group'].unique()]
grouped_data

[0       2.5
 13      3.2
 14      3.0
 19      2.6
 20      3.1
        ...
 4813    2.7
 4814    2.2
 4815    2.9
 4995    3.3
 5000    3.1
 Name: Mean_Q1, Length: 695, dtype: float64,
 2       3.4
 5       2.6
 8       3.3
 9       2.9
 21      3.1
        ...
 5141    2.9
 5145    3.6
 5150    2.9
 5254    2.9
 5268    3.3
 Name: Mean_Q1, Length: 891, dtype: float64,
 3       2.9
 12      2.9
 22      2.8
 29      3.0
 38      3.2
        ...
 5144    3.4
 5146    3.7
 5149    3.6
 5151    3.6
 5152    3.3
 Name: Mean_Q1, Length: 979, dtype: float64,
 4       2.9
 6       2.9
 11      2.4
 15      3.2
 16      3.3
        ...
 5368    3.4
 5370    3.3
 5372    3.3
 5374    2.5
 5376    3.3
 Name: Mean_Q1, Length: 871, dtype: float64,
 17      3.0
 25      2.7
 75      3.8
 98      2.2
 113     2.5
        ...
 5369    3.4
 5371    3.4
 5373    3.3
 5375    3.5
 5377    2.5
 Name: Mean_Q1, Length: 295, dtype: float64,
 26      3.3
 27      2.8
 31      3.0
 32      3.2
 34      2.9
        ...
 5065    3.6
 5067    3.4
 5105    3.4
 5128    2.9
 5135    3.5
 Name: Mean_Q1, Length: 836, dtype: float64]

In [16]:
f_val, p_val = stats.f_oneway(*grouped_data)
print(f"ANOVA 결과: F-통계량 = {f_val}, p-값 = {p_val}")

ANOVA 결과: F-통계량 = 188.1821771611334, p-값 = 1.0233904880339432e-182

In [18]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [22]:
tukey = pairwise_tukeyhsd(endog=df_mean['Mean_Q1'],
                          groups=df_mean['Age_group'],
                          alpha=0.05)
print(tukey) #투키

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   0.1045 0.0737 -0.0055  0.2144  False
     1      3   -0.066 0.5458 -0.1781  0.0461  False
     1      4  -0.1258 0.0164 -0.2374 -0.0143   True
     1      5  -0.3921    0.0 -0.5033 -0.2809   True
     1      6  -0.6831    0.0 -0.7981 -0.5681   True
     2      3  -0.1705    0.0 -0.2484 -0.0925   True
     2      4  -0.2303    0.0 -0.3074 -0.1532   True
     2      5  -0.4965    0.0 -0.5732 -0.4199   True
     2      6  -0.7875    0.0 -0.8697 -0.7054   True
     3      4  -0.0598  0.273   -0.14  0.0203  False
     3      5  -0.3261    0.0 -0.4058 -0.2464   True
     3      6  -0.6171    0.0  -0.702 -0.5321   True
     4      5  -0.2662    0.0 -0.3451 -0.1874   True
     4      6  -0.5572    0.0 -0.6414  -0.473   True
     5      6   -0.291    0.0 -0.3748 -0.2072   True
----------------------------------------------------

In [27]:
!pip install statsmodels scikit-posthocs
!pip install pingouin
import pingouin as pg

Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (0.14.2)
Requirement already satisfied: scikit-posthocs in /usr/local/lib/python3.10/dist-packages (0.9.0)
Requirement already satisfied: numpy>=1.22.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.26.4)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.13.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (2.1.4)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (0.5.6)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (24.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from scikit-posthocs) (0.13.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from scikit-posthocs) (3.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.6->statsmodels) (1.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->scikit-posthocs) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->scikit-posthocs) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->scikit-posthocs) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->scikit-posthocs) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->scikit-posthocs) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->scikit-posthocs) (3.1.2)
Collecting pingouin
  Downloading pingouin-0.5.4-py2.py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.13.1)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.10/dist-packages (from pingouin) (2.1.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from pingouin) (3.7.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.13.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.14.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.3.2)
Collecting pandas-flavor (from pingouin)
  Downloading pandas_flavor-0.6.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->pingouin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->pingouin) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->pingouin) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (3.1.2)
Requirement already satisfied: xarray in /usr/local/lib/python3.10/dist-packages (from pandas-flavor->pingouin) (2024.6.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pingouin) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pingouin) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels->pingouin) (0.5.6)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.6->statsmodels->pingouin) (1.16.0)
Downloading pingouin-0.5.4-py2.py3-none-any.whl (198 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.9/198.9 kB 4.3 MB/s eta 0:00:00
Downloading pandas_flavor-0.6.0-py3-none-any.whl (7.2 kB)
Installing collected packages: pandas-flavor, pingouin
Successfully installed pandas-flavor-0.6.0 pingouin-0.5.4

In [29]:
duncan_result = pg.pairwise_tukey(dv='Mean_Q1', between='Age_group', data=df_mean)
print(duncan_result)

    A  B   mean(A)   mean(B)      diff        se          T       p-tukey  \
0   1  2  3.291864  3.396323 -0.104458  0.038567  -2.708506  7.371699e-02
1   1  3  3.291864  3.225837  0.066027  0.039323   1.679089  5.457577e-01
2   1  4  3.291864  3.166016  0.125848  0.039117   3.217267  1.643095e-02
3   1  5  3.291864  2.899776  0.392089  0.039005  10.052195  2.792877e-12
4   1  6  3.291864  2.608777  0.683087  0.040350  16.928987  2.792877e-12
5   2  3  3.396323  3.225837  0.170485  0.027345   6.234654  7.401002e-09
6   2  4  3.396323  3.166016  0.230307  0.027047   8.515105  2.793099e-12
7   2  5  3.396323  2.899776  0.496547  0.026886  18.468807  2.792877e-12
8   2  6  3.396323  2.608777  0.787546  0.028802  27.343286  2.792877e-12
9   3  4  3.225837  3.166016  0.059821  0.028115   2.127746  2.730214e-01
10  3  5  3.225837  2.899776  0.326062  0.027960  11.661773  2.792877e-12
11  3  6  3.225837  2.608777  0.617060  0.029807  20.701625  2.792877e-12
12  4  5  3.166016  2.899776  0.266241  0.027669   9.622502  2.792877e-12
13  4  6  3.166016  2.608777  0.557239  0.029534  18.867573  2.792877e-12
14  5  6  2.899776  2.608777  0.290999  0.029387   9.902375  2.792877e-12

      hedges
0  -0.254827
1   0.137534
2   0.246783
3   0.620735
4   0.972074
5   0.374712
6   0.484377
7   0.885488
8   1.311614
9   0.114645
10  0.537898
11  0.946928
12  0.429488
13  0.837884
14  0.394610

2. 일원분산분석 시행

In [ ]:
from scipy.stats import f_oneway

In [46]:
df = pd.DataFrame(csv_test)
columns_to_check = ['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']
filtered_df = df[~df[columns_to_check].isin([9]).any(axis=1)]
filtered_df
filtered_df[['Age_group', 'Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1 = filtered_df[['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1 = np.mean(df1, axis=1)

In [47]:
agedata = filtered_df[['Age_group']]
df1 = pd.concat([df1, agedata], axis=1)
df1.columns = ['mean', 'Age_group']
df1

      mean  Age_group
0      2.5          6
2      3.4          5
3      2.9          2
4      2.9          4
5      2.6          5
...    ...        ...
5373   3.3          1
5374   2.5          4
5375   3.5          1
5376   3.3          4
5377   2.5          1

[4567 rows x 2 columns]

In [ ]:
grouped_data = df1.groupby('Age_group')['mean'].apply(list)
print(grouped_data)

Age_group
1    [3.0, 2.7, 3.8, 2.2, 2.5, 4.0, 3.6, 2.9, 3.8, ...
2    [2.9, 2.9, 2.8, 3.0, 3.2, 3.6, 3.7, 3.4, 3.7, ...
3    [3.3, 2.8, 3.0, 3.2, 2.9, 2.6, 2.6, 3.2, 2.9, ...
4    [2.9, 2.9, 2.4, 3.2, 3.3, 3.2, 3.4, 3.4, 3.7, ...
5    [3.4, 2.6, 3.3, 2.9, 3.1, 2.7, 2.8, 2.8, 3.2, ...
6    [2.5, 3.2, 3.0, 2.6, 3.1, 3.1, 2.5, 2.7, 2.4, ...
Name: mean, dtype: object

In [ ]:
f_statistic, p_value = f_oneway(*grouped_data)
print("일원분산분석(One-way ANOVA) 결과:")
print("F 통계량:", f_statistic)
print("p-value:", p_value)

일원분산분석(One-way ANOVA) 결과:
F 통계량: 188.18217716113347
p-value: 1.0233904880339432e-182

3. 회귀분석 시행

In [73]:
df1_1

,Age_group,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q1_8,Q1_9,Q1_10,Mean_Q1
0,1,3.193220,3.162712,3.071186,3.247458,3.464407,3.532203,3.433898,3.488136,3.081356,3.244068,3.291864
1,2,3.324821,3.339122,3.185904,3.366701,3.467824,3.582227,3.561798,3.534219,3.187947,3.412666,3.396323
2,3,3.159091,3.244019,2.984450,3.116029,3.299043,3.461722,3.436603,3.423445,2.952153,3.181818,3.225837
3,4,3.072331,3.171068,2.887486,3.044776,3.316877,3.417910,3.437428,3.396096,2.840413,3.075775,3.166016
4,5,2.817059,2.925926,2.603816,2.769921,3.016835,3.184063,3.190797,3.115600,2.566779,2.806958,2.899776
5,6,2.505036,2.657554,2.279137,2.458993,2.729496,2.877698,2.943885,2.797122,2.300719,2.538129,2.608777

In [75]:
columns_to_check = ['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']
df_mean_q1 = df1_1
df_mean_q1['Mean_Q1'] = df1_1[columns_to_check].mean(axis=1)
print(df_mean_q1)

   Age_group      Q1_1      Q1_2      Q1_3      Q1_4      Q1_5      Q1_6  \
0          1  3.193220  3.162712  3.071186  3.247458  3.464407  3.532203
1          2  3.324821  3.339122  3.185904  3.366701  3.467824  3.582227
2          3  3.159091  3.244019  2.984450  3.116029  3.299043  3.461722
3          4  3.072331  3.171068  2.887486  3.044776  3.316877  3.417910
4          5  2.817059  2.925926  2.603816  2.769921  3.016835  3.184063
5          6  2.505036  2.657554  2.279137  2.458993  2.729496  2.877698

       Q1_7      Q1_8      Q1_9     Q1_10   Mean_Q1
0  3.433898  3.488136  3.081356  3.244068  3.291864
1  3.561798  3.534219  3.187947  3.412666  3.396323
2  3.436603  3.423445  2.952153  3.181818  3.225837
3  3.437428  3.396096  2.840413  3.075775  3.166016
4  3.190797  3.115600  2.566779  2.806958  2.899776
5  2.943885  2.797122  2.300719  2.538129  2.608777

3. 주요변수 기술 통계 - 독립변수

In [ ]:
import pandas as pd
from scipy import stats

In [ ]:
data = pd.read_csv('/content/2022_2022년 지능정보사회 이용자 패널 조사_Data(가중치포함).csv')
df = pd.DataFrame(data)
df=df[['Age_group', 'DQ2_1', 'DQ6', 'DQ7']]
age_group_6 = df[df['Age_group'] == 6]
age_group_6

      Age_group  DQ2_1  DQ6  DQ7
0             6      4    4    3
10            6      4    4    3
13            6      4    8    3
14            6      4    8    3
19            6      6    6    4
...         ...    ...  ...  ...
4814          6      4    5    5
4815          6      4   10    3
4995          6      4    3    5
5000          6      3    4    5
5084          6      6    7    2

[823 rows x 4 columns]

In [ ]:
def descriptive_statistics(df):
    stats_summary = pd.DataFrame(index=['mean', 'std', 'skewness', 'kurtosis'])

    stats_summary['DQ2_1'] = [
        df['DQ2_1'].mean(),
        df['DQ2_1'].std(),
        stats.skew(df['DQ2_1']),
        stats.kurtosis(df['DQ2_1'])
    ]

    stats_summary['DQ6'] = [
        df['DQ6'].mean(),
        df['DQ6'].std(),
        stats.skew(df['DQ6']),
        stats.kurtosis(df['DQ6'])
    ]

    stats_summary['DQ7'] = [
        df['DQ7'].mean(),
        df['DQ7'].std(),
        stats.skew(df['DQ7']),
        stats.kurtosis(df['DQ7'])
    ]

    return stats_summary

In [ ]:
stats_summary = descriptive_statistics(df)
print(stats_summary)

             DQ2_1       DQ6       DQ7
mean      4.970249  6.299740  3.556341
std       0.985221  1.800999  0.684240
skewness -0.228727  0.130223  0.045453
kurtosis -1.065942 -0.474224 -0.123663

4. 주요변수 기술 통계 - 기술사용의사

In [ ]:
columns_to_check = ['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']
filtered_df = df[~df[columns_to_check].isin([9]).any(axis=1)]
print(filtered_df)
filtered_df.columns
filtered_df[['Age_group', 'Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1 = filtered_df[['Age_group', 'Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1

        No         wgt_a     wgt_b        id       Josagu  Josagu_gubun  Bon  \
0        1   9115.936286  1.249960       2_1  11010730061             2    1
2        3  11069.130680  1.517778       8_2  11010730061             2    1
3        4   5461.096385  0.748815       8_3  11010730061             2    1
4        5   2308.647665  0.316557       9_1  11010730061             2    1
5        6   7379.420451  1.011852      10_1  11010730061             2    1
...    ...           ...       ...       ...          ...           ...  ...
5373  5374   5214.785929  0.715042  204405_2  11250730521             2    2
5374  5375   3682.940899  0.504998  204411_1  11250730521             2    2
5375  5376   5807.987516  0.796380  204411_2  11250730521             2    2
5376  5377   2455.293933  0.336665  204417_1  11250730521             2    2
5377  5378   3476.523952  0.476694  204417_2  11250730521             2    2

      Area1  Area2  Area3  ...  DQ4_2  DQ4_3  DQ4_4  DQ4_op2  DQ4_op3  \
0         1    113      3  ...    NaN    NaN    NaN      NaN      NaN
2         1    113      3  ...    NaN    NaN    4.0      NaN      NaN
3         1    113      3  ...    NaN    NaN    NaN      NaN      NaN
4         1    113      3  ...    NaN    NaN    NaN      NaN      NaN
5         1    113      3  ...    NaN    NaN    NaN      NaN      NaN
...     ...    ...    ...  ...    ...    ...    ...      ...      ...
5373      1    116      3  ...    NaN    NaN    NaN      NaN      NaN
5374      1    116      3  ...    NaN    3.0    NaN      NaN      1.0
5375      1    116      3  ...    NaN    NaN    NaN      NaN      NaN
5376      1    116      3  ...    NaN    3.0    NaN      NaN      1.0
5377      1    116      3  ...    NaN    NaN    NaN      NaN      NaN

      DQ4_op4  DQ5  DQ6  DQ7  Mean_Q1
0         NaN    4    4    3      2.5
2         1.0    6   10    3      3.4
3         NaN    7   10    3      2.9
4         NaN    5    5    4      2.9
5         NaN    4    4    5      2.6
...       ...  ...  ...  ...      ...
5373      NaN   11   10    4      3.3
5374      NaN    5   10    4      2.5
5375      NaN   11   10    4      3.5
5376      NaN    7    7    4      3.3
5377      NaN   11    7    4      2.5

[4567 rows x 405 columns]

      Age_group  Q1_1  Q1_2  Q1_3  Q1_4  Q1_5  Q1_6  Q1_7  Q1_8  Q1_9  Q1_10
0             6     3     2     1     3     2     2     3     4     3      2
2             5     4     3     3     4     3     4     3     3     4      3
3             2     3     2     3     3     2     4     3     3     3      3
4             4     3     3     2     3     4     4     3     2     2      3
5             5     3     3     2     1     3     3     4     3     2      2
...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
5373          1     3     3     3     3     4     4     4     4     2      3
5374          4     2     2     2     2     3     3     3     3     2      3
5375          1     3     3     3     4     4     4     4     4     3      3
5376          4     3     3     3     3     4     4     4     4     2      3
5377          1     2     2     2     2     3     3     3     3     2      3

[4567 rows x 11 columns]

In [ ]:
age_group_6 =df1[df1['Age_group'] == 6]
age_group_6
#filtered_df = age_group_6[['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
#filtered_df

      Age_group  Q1_1  Q1_2  Q1_3  Q1_4  Q1_5  Q1_6  Q1_7  Q1_8  Q1_9  Q1_10
0             6     3     2     1     3     2     2     3     4     3      2
13            6     3     3     2     4     4     3     2     4     3      4
14            6     3     3     2     4     4     3     2     3     3      3
19            6     3     3     2     3     4     2     2     3     2      2
20            6     3     2     3     3     4     4     3     2     4      3
...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
4813          6     3     3     2     3     4     3     3     2     2      2
4814          6     2     2     2     2     2     2     2     3     2      3
4815          6     3     3     3     2     3     3     4     3     3      2
4995          6     4     4     3     2     3     3     4     4     3      3
5000          6     4     4     4     2     2     3     3     1     4      4

[695 rows x 11 columns]

In [ ]:
df_mean_q1 = pd.DataFrame()
df_mean_q1['Mean_Q1'] = age_group_6[columns_to_check].mean(axis=1)
print(df_mean_q1)

      Mean_Q1
0         2.5
13        3.2
14        3.0
19        2.6
20        3.1
...       ...
4813      2.7
4814      2.2
4815      2.9
4995      3.3
5000      3.1

[695 rows x 1 columns]

In [ ]:
def descriptive_statistics(df):
    stats_summary = pd.DataFrame(index=['mean', 'std', 'skewness', 'kurtosis'])

    stats_summary['Mean_Q1'] = [
        df['Mean_Q1'].mean(),
        df['Mean_Q1'].std(),
        stats.skew(df['Mean_Q1']),
        stats.kurtosis(df['Mean_Q1'])
    ]

    return stats_summary

In [ ]:
stats_summary = descriptive_statistics(df)
print(stats_summary)

           Mean_Q1
mean      3.387821
std       1.053029
skewness  1.636487
kurtosis  6.377612