<a href="https://colab.research.google.com/github/abalckpie/professorahn/blob/main/%EC%86%8C%EB%85%BC%EB%AC%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
csv_test = pd.read_csv('/content/2022_2022년 지능정보사회 이용자 패널 조사_Data(가중치포함).csv')
df = pd.DataFrame(csv_test)
df

,No,wgt_a,wgt_b,id,Josagu,Josagu_gubun,Bon,Area1,Area2,Area3,...,DQ4_1,DQ4_2,DQ4_3,DQ4_4,DQ4_op2,DQ4_op3,DQ4_op4,DQ5,DQ6,DQ7
0,1,9115.936286,1.249960,2_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3
1,2,7379.420451,1.011852,6_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4,4,5
2,3,11069.130680,1.517778,8_2,11010730061,2,1,1,113,3,...,NaN,NaN,NaN,4.0,NaN,NaN,1.0,6,10,3
3,4,5461.096385,0.748815,8_3,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,7,10,3
4,5,2308.647665,0.316557,9_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373,5374,5214.785929,0.715042,204405_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,10,4
5374,5375,3682.940899,0.504998,204411_1,11250730521,2,2,1,116,3,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,5,10,4
5375,5376,5807.987516,0.796380,204411_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,10,4
5376,5377,2455.293933,0.336665,204417_1,11250730521,2,2,1,116,3,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,7,7,4
5377,5378,3476.523952,0.476694,204417_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,7,4

1. 연령별 평균치 확인

In [4]:
df.columns
df[['Age_group', 'Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1 = df[['Age_group', 'Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1

      Age_group  Q1_1  Q1_2  Q1_3  Q1_4  Q1_5  Q1_6  Q1_7  Q1_8  Q1_9  Q1_10
0             6     3     2     1     3     2     2     3     4     3      2
1             5     3     2     2     4     9     4     2     2     3      3
2             5     4     3     3     4     3     4     3     3     4      3
3             2     3     2     3     3     2     4     3     3     3      3
4             4     3     3     2     3     4     4     3     2     2      3
...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
5373          1     3     3     3     3     4     4     4     4     2      3
5374          4     2     2     2     2     3     3     3     3     2      3
5375          1     3     3     3     4     4     4     4     4     3      3
5376          4     3     3     3     3     4     4     4     4     2      3
5377          1     2     2     2     2     3     3     3     3     2      3

[5378 rows x 11 columns]

In [5]:
df1.groupby(by='Age_group').mean().reset_index()
df1_1=df1.groupby(by='Age_group').mean().reset_index()
df1_1

,Age_group,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q1_8,Q1_9,Q1_10
0,1,3.292308,3.301538,3.320000,3.418462,3.556923,3.621538,3.523077,3.643077,3.286154,3.446154
1,2,3.428699,3.482175,3.427807,3.559715,3.559715,3.682709,3.688057,3.663102,3.467023,3.544563
2,3,3.328947,3.370445,3.440283,3.493927,3.441296,3.603239,3.580972,3.561741,3.345142,3.434211
3,4,3.386473,3.445411,3.348792,3.480193,3.491787,3.583575,3.628986,3.563285,3.365217,3.420290
4,5,3.355760,3.230415,3.250691,3.299539,3.298618,3.410138,3.440553,3.339171,3.206452,3.220276
5,6,3.109356,3.012151,2.900365,3.032807,3.065614,3.114216,3.206561,3.051033,3.044957,3.087485

In [6]:
del df1_1['Age_group']
df1_1.mean(axis='columns')

0    3.440923
1    3.550357
2    3.460020
3    3.471401
4    3.305161
5    3.062454
dtype: float64

2. 일원분산분석 시행

In [11]:
from scipy.stats import f_oneway

In [13]:
df = pd.DataFrame(csv_test)
df.columns
df[['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1 = df[['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
df1 = np.mean(df1, axis=1)

In [8]:
agedata = df[['Age_group']]
df1 = pd.concat([df1, agedata], axis=1)
df1.columns = ['mean', 'Age_group']
df1

      mean  Age_group
0      2.5          6
1      3.4          5
2      3.4          5
3      2.9          2
4      2.9          4
...    ...        ...
5373   3.3          1
5374   2.5          4
5375   3.5          1
5376   3.3          4
5377   2.5          1

[5378 rows x 2 columns]

In [9]:
grouped_data = df1.groupby('Age_group')['mean'].apply(list)
print(grouped_data)

Age_group
1    [3.0, 2.7, 3.8, 2.2, 2.5, 4.0, 3.6, 2.9, 3.8, ...
2    [2.9, 2.9, 3.7, 2.8, 3.0, 3.2, 3.6, 3.7, 3.4, ...
3    [3.3, 2.8, 3.0, 3.2, 2.9, 2.6, 2.6, 3.2, 2.9, ...
4    [2.9, 2.9, 2.4, 3.2, 3.3, 4.4, 3.2, 3.8, 3.4, ...
5    [3.4, 3.4, 2.6, 3.9, 3.3, 2.9, 3.1, 2.7, 2.8, ...
6    [2.5, 3.4, 3.2, 3.0, 2.6, 3.1, 3.1, 2.5, 2.7, ...
Name: mean, dtype: object

In [12]:
f_statistic, p_value = f_oneway(*grouped_data)
print("일원분산분석(One-way ANOVA) 결과:")
print("F 통계량:", f_statistic)
print("p-value:", p_value)

일원분산분석(One-way ANOVA) 결과:
F 통계량: 25.35740027922788
p-value: 2.3077526887078017e-25