<a href="https://colab.research.google.com/github/abalckpie/professorahn/blob/main/%EC%86%8C%EB%85%BC%EB%AC%B8_3%EC%A0%88_%EB%B3%80%EC%88%98%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas as pd
import numpy as np
import scipy.stats as stats
csv_test = pd.read_csv('/content/2022_2022년 지능정보사회 이용자 패널 조사_Data(가중치포함).csv')
df = pd.DataFrame(csv_test)
df

,No,wgt_a,wgt_b,id,Josagu,Josagu_gubun,Bon,Area1,Area2,Area3,...,DQ4_1,DQ4_2,DQ4_3,DQ4_4,DQ4_op2,DQ4_op3,DQ4_op4,DQ5,DQ6,DQ7
0,1,9115.936286,1.249960,2_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3
1,2,7379.420451,1.011852,6_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4,4,5
2,3,11069.130680,1.517778,8_2,11010730061,2,1,1,113,3,...,NaN,NaN,NaN,4.0,NaN,NaN,1.0,6,10,3
3,4,5461.096385,0.748815,8_3,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,7,10,3
4,5,2308.647665,0.316557,9_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373,5374,5214.785929,0.715042,204405_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,10,4
5374,5375,3682.940899,0.504998,204411_1,11250730521,2,2,1,116,3,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,5,10,4
5375,5376,5807.987516,0.796380,204411_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,10,4
5376,5377,2455.293933,0.336665,204417_1,11250730521,2,2,1,116,3,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,7,7,4
5377,5378,3476.523952,0.476694,204417_2,11250730521,2,2,1,116,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,11,7,4

In [57]:
columns_to_check = ['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']
df = df[~df[columns_to_check].isin([9]).any(axis=1)]
df=df[['Age_group', 'DQ2_1', 'DQ6', 'DQ7']]
age_group_6 = df[df['Age_group'] == 6]
age_group_6

      Age_group  DQ2_1  DQ6  DQ7
0             6      4    4    3
13            6      4    8    3
14            6      4    8    3
19            6      6    6    4
20            6      5    6    4
...         ...    ...  ...  ...
4813          6      4    8    3
4814          6      4    5    5
4815          6      4   10    3
4995          6      4    3    5
5000          6      3    4    5

[695 rows x 4 columns]

In [58]:
def descriptive_statistics(age_group_6):
    stats_summary = pd.DataFrame(index=['mean', 'std', 'skewness', 'kurtosis'])

    stats_summary['DQ2_1'] = [
        df['DQ2_1'].mean(),
        df['DQ2_1'].std(),
        stats.skew(df['DQ2_1']),
        stats.kurtosis(df['DQ2_1'])
    ]

    stats_summary['DQ6'] = [
        df['DQ6'].mean(),
        df['DQ6'].std(),
        stats.skew(df['DQ6']),
        stats.kurtosis(df['DQ6'])
    ]

    stats_summary['DQ7'] = [
        df['DQ7'].mean(),
        df['DQ7'].std(),
        stats.skew(df['DQ7']),
        stats.kurtosis(df['DQ7'])
    ]

    return stats_summary

In [59]:
stats_summary = descriptive_statistics(df)
print(stats_summary)

             DQ2_1       DQ6       DQ7
mean      4.972411  6.354062  3.537114
std       0.981935  1.805385  0.674850
skewness -0.237713  0.122623  0.057448
kurtosis -1.096948 -0.476580 -0.160748

60대 이상 기술사용의사변수 기술통계

In [66]:
import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis

In [67]:
df = df = pd.DataFrame(csv_test)
columns_to_check = ['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']
df = df[~df[columns_to_check].isin([9]).any(axis=1)]
age_group_6 = df[df['Age_group'] == 6]
age_group_6

,No,wgt_a,wgt_b,id,Josagu,Josagu_gubun,Bon,Area1,Area2,Area3,...,DQ4_1,DQ4_2,DQ4_3,DQ4_4,DQ4_op2,DQ4_op3,DQ4_op4,DQ5,DQ6,DQ7
0,1,9115.936286,1.249960,2_1,11010730061,2,1,1,113,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3
13,14,11810.788630,1.619473,50_1,11020710091,2,1,1,114,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5,8,3
14,15,9115.936286,1.249960,50_2,11020710091,2,1,1,114,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5,8,3
19,20,11810.788630,1.619473,61_1,11020710091,2,1,1,114,3,...,NaN,NaN,NaN,4.0,NaN,NaN,2.0,4,6,4
20,21,9115.936286,1.249960,61_2,11020710091,2,1,1,114,3,...,NaN,NaN,NaN,4.0,NaN,NaN,2.0,3,6,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4813,4814,7905.030310,1.083923,202166_2,3103064059A,1,2,9,825,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,6,8,3
4814,4815,7905.030310,1.083923,202169_1,3103064059A,1,2,9,825,3,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5,5,5
4815,4816,9786.389640,1.341891,202170_1,3103064059A,1,2,9,825,3,...,NaN,NaN,NaN,4.0,NaN,NaN,1.0,5,10,3
4995,4996,6864.488162,0.941246,202967_1,31180520071,2,2,9,830,3,...,NaN,NaN,NaN,4.0,NaN,NaN,1.0,3,3,5
5000,5001,6864.488162,0.941246,202974_2,31180520071,2,2,9,830,3,...,NaN,NaN,NaN,4.0,NaN,NaN,1.0,11,4,5

In [68]:
age_group_6 = age_group_6[['Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10']]
age_group_6

      Q1_1  Q1_2  Q1_3  Q1_4  Q1_5  Q1_6  Q1_7  Q1_8  Q1_9  Q1_10
0        3     2     1     3     2     2     3     4     3      2
13       3     3     2     4     4     3     2     4     3      4
14       3     3     2     4     4     3     2     3     3      3
19       3     3     2     3     4     2     2     3     2      2
20       3     2     3     3     4     4     3     2     4      3
...    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
4813     3     3     2     3     4     3     3     2     2      2
4814     2     2     2     2     2     2     2     3     2      3
4815     3     3     3     2     3     3     4     3     3      2
4995     4     4     3     2     3     3     4     4     3      3
5000     4     4     4     2     2     3     3     1     4      4

[695 rows x 10 columns]

In [69]:
age_group_6_mean = pd.DataFrame(age_group_6)
age_group_6_mean['Mean_Q1'] = age_group_6_mean.mean(axis=1)
#age_group_6_mean = age_group_6_mean.loc[:,['Mean_Q1']]
age_group_6_mean

      Q1_1  Q1_2  Q1_3  Q1_4  Q1_5  Q1_6  Q1_7  Q1_8  Q1_9  Q1_10  Mean_Q1
0        3     2     1     3     2     2     3     4     3      2      2.5
13       3     3     2     4     4     3     2     4     3      4      3.2
14       3     3     2     4     4     3     2     3     3      3      3.0
19       3     3     2     3     4     2     2     3     2      2      2.6
20       3     2     3     3     4     4     3     2     4      3      3.1
...    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...      ...
4813     3     3     2     3     4     3     3     2     2      2      2.7
4814     2     2     2     2     2     2     2     3     2      3      2.2
4815     3     3     3     2     3     3     4     3     3      2      2.9
4995     4     4     3     2     3     3     4     4     3      3      3.3
5000     4     4     4     2     2     3     3     1     4      4      3.1

[695 rows x 11 columns]

In [71]:
mean_val = age_group_6_mean['Mean_Q1'].mean()
std_dev = age_group_6_mean['Mean_Q1'].std()
skewness = skew(age_group_6_mean['Mean_Q1'])
kurt = kurtosis(age_group_6_mean['Mean_Q1'])

print(f"Mean: {mean_val}")
print(f"Standard Deviation: {std_dev}")
print(f"Skewness: {skewness}")
print(f"Kurtosis: {kurt}")

Mean: 2.608776978417266
Standard Deviation: 0.7943935939936682
Skewness: -0.38687653699727514
Kurtosis: -0.9803840132586163